services:
    partkeepr.iri_converter:
        alias: api_platform.iri_converter
        public: true
    PartKeepr\AuthBundle\Security\Authentication\AuthenticationProviderManager:
        alias: security.authentication.manager
        public: true